### ISSUE TITLE
feature request: delayed smart tax or "additional tax burden"

### ISSUE THREAD

**Issue by DanielKispert** [thomasfn/EcoSmartTaxMod#5]
with the tax framework, we were able to have the actual tree tax delayed until the next tax framework tick, so you were unaffected by it if you cleaned up your stuff fast enough. Smart Tax is collecting instantly, meaning a citizen will get taxed immediately.
That means we also have to do a "smart pay" instead of a "smart rebate" for giving back the money that was taxed, because otherwise citizens will be taxed their money but not given it back. The government has to actually give out money instead of future tax income.
It would be awesome if there was a way to delay a "smart tax" action without having to resort to the tax framework again, by e.g. saying "trigger 1h afterwards". Alternatively, there could be a counterpiece to the smart rebate to increase the tax burden for you by a certain amount but not collect these taxes immediately.
If the current "smart rebate" can already handle negative numbers (meaning, additional tax debt) then maybe it can be renamed to a "smart tax difference" or something like that to reflect that it can do both positive and negative changes in tax burden

**Comment by thomasfn** [comment]
Fixed in #7
